#注意如果在记事本上编写，下面的缩进不能用Tab键不然会报错要用2个空格
spring:
  porfiles:
    active: dev #激活开发环境配置
    
---
server:
  port: 6001 #端口号
spring:
  porfiles: dev #开发环境
  application:
    name: microservice-config-eureka #项目名称


eureka:
  instance:
    hostname: eureka6001.com # eureka服务端的实例名称
  client:
    registerWithEureka: false      # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: false           # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:                    # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自 己（如果不配置则默认本机8761端口）
      defaultZone: http://eureka6002.com:6002/eureka/
    server:
      enable-self-preservation: false # 禁用自我保护模式
      
---
server:
  port: 6001 #端口号
spring:
  porfiles: prod #生产环境
  application:
    name: microservice-config-eureka #项目名称


eureka:
  instance:
    hostname: eureka6001.com # eureka服务端的实例名称
  client:
    registerWithEureka: false      # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: false           # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:                    # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自 己（如果不配置则默认本机8761端口）
      defaultZone: http://eureka6002.com:6002/eureka/
    server:
      enable-self-preservation: true # 禁用自我保护模式

#注意记事本保存，选择utf-8